# =============================================================================
# KitaevHoneycomb - closed-form / TL / scaling / OBC validation (testsets 1-7 of 12)
#
# Split out of test/models/quantum/KitaevHoneycomb/test_KitaevHoneycomb.jl
# (2.5 min on s06) so each top-level group runs on its own shard.
# =============================================================================

using QAtlas: KitaevHoneycomb, Energy, MassGap, Infinite, PBC, OBC
using Test
using LinearAlgebra: eigvals, Hermitian, I as I_mat
using SparseArrays: sparse, spzeros
using KrylovKit: eigsolve
using Lattice2D: build_lattice, Honeycomb, OpenAxis, PeriodicAxis
using LatticeCore: num_sites, bonds

# Reference value taken from Baskaran, Mandal & Shankar (PRL 98, 247201)
# and reproduced in Feng et al. DMRG benchmarks of the Kitaev model:
# at the isotropic point (Kx = Ky = Kz = 1) the ground state energy
# per site for H = -Σ Kγ σγ σγ is
#
#     ε₀ ≈ -0.7872986...
#
# i.e. `-⟨|f(k)|⟩ / 2` in the conventions of the module.

const ε_isotropic_TL = -0.7872986216706852

@testset "KitaevHoneycomb: TL isotropic matches -<|f|>/2" begin
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    E = QAtlas.fetch(m, Energy(), Infinite())
    @test E ≈ ε_isotropic_TL rtol = 1e-6
end

@testset "KitaevHoneycomb: PBC finite-size scaling → TL (Kx=Ky=Kz=1)" begin
    # Per `md/testing.md` §4 (limit tests): verify the discrete Bloch sum
    # converges to the TL value with tightening tolerance as `L` grows.
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    E_TL = QAtlas.fetch(m, Energy(), Infinite())

    Ls = (8, 16, 32)
    E_pbc = [QAtlas.fetch(m, Energy(), PBC(0); Lx=L, Ly=L) for L in Ls]
    # Loose bound at every L; shrinks monotonically with L.
    for (L, E) in zip(Ls, E_pbc)
        @test abs(E - E_TL) < 1e-3
    end
    # Coarse rate check: the L=32 residual is at least 10× smaller than
    # L=8 (exact scaling is ~1/L² but we leave room for the approach).
    @test abs(E_pbc[end] - E_TL) * 10 < abs(E_pbc[1] - E_TL)
end

@testset "KitaevHoneycomb: OBC finite-size scaling approaches TL from above" begin
    # Open boundaries lose some bonds → |E| per site *smaller* than TL;
    # the gap should shrink monotonically as Lx = Ly = L grows.
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    E_TL = QAtlas.fetch(m, Energy(), Infinite())
    E_obc = [QAtlas.fetch(m, Energy(), OBC(0); Lx=L, Ly=L) for L in 1:8]

    # All OBC values are above (less negative than) the TL value.
    for E in E_obc
        @test E > E_TL
    end
    # Monotone approach: each step moves closer to the TL value.
    for k in 1:(length(E_obc) - 1)
        @test E_obc[k + 1] < E_obc[k]                # more negative
        @test abs(E_obc[k + 1] - E_TL) < abs(E_obc[k] - E_TL)
    end
end

@testset "KitaevHoneycomb: OBC finite values are well-defined and negative" begin
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    # Known reference values from the flux-free-sector ansatz on small
    # Lx × Ly OBC strips (L1·L2 unit cells → 2·L1·L2 sites).
    # These were generated by running the same code — freezing them
    # here protects against accidental regressions.
    @test QAtlas.fetch(m, Energy(), OBC(0); Lx=2, Ly=2) ≈ -0.5832335726130254 rtol = 1e-12
    @test QAtlas.fetch(m, Energy(), OBC(0); Lx=3, Ly=3) ≈ -0.6304009569087188 rtol = 1e-12
end

@testset "KitaevHoneycomb: positivity & linearity under coupling scaling" begin
    # Per testing.md §2 (sanity): H ∝ K ⇒ E ∝ K. Doubling every coupling
    # doubles the ground state energy; halving halves it.
    m1 = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    m2 = KitaevHoneycomb(; Kx=2.0, Ky=2.0, Kz=2.0)
    m_half = KitaevHoneycomb(; Kx=0.5, Ky=0.5, Kz=0.5)
    E1 = QAtlas.fetch(m1, Energy(), Infinite())
    E2 = QAtlas.fetch(m2, Energy(), Infinite())
    E_half = QAtlas.fetch(m_half, Energy(), Infinite())
    @test E2 ≈ 2 * E1 rtol = 1e-8
    @test E_half ≈ E1 / 2 rtol = 1e-8
    # Kitaev's own |K_γ| ≤ 1/2 convention at isotropic K = 0.5 has a
    # published value of ≈ -0.3936 per site; this is exactly E1 / 2.
    @test E_half ≈ -0.3936493108353426 rtol = 1e-8

    # Zero-coupling limit: H = 0 ⇒ E = 0. (testing.md §4)
    E0 = QAtlas.fetch(KitaevHoneycomb(; Kx=0.0, Ky=0.0, Kz=0.0), Energy(), Infinite())
    @test E0 ≈ 0.0 atol = 1e-12
end

@testset "KitaevHoneycomb: MassGap follows the phase diagram" begin
    # Isotropic / generic gapless (B-phase): all |Kγ| ≤ sum of the others.
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0), MassGap(), Infinite()) ==
        0.0
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=0.8, Ky=1.0, Kz=1.1), MassGap(), Infinite()) ==
        0.0

    # Az phase: Kz > Kx + Ky ⇒ Δ = 2·(Kz − Kx − Ky).
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=0.5, Ky=0.5, Kz=2.0), MassGap(), Infinite()) ≈
        2.0 rtol = 1e-12

    # Ax phase: Kx > Ky + Kz.
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=2.0, Ky=0.5, Kz=0.5), MassGap(), Infinite()) ≈
        2.0 rtol = 1e-12
end

@testset "KitaevHoneycomb: OBC argument validation" begin
    m = KitaevHoneycomb()
    @test_throws ErrorException QAtlas.fetch(m, Energy(), OBC(0); Lx=0, Ly=4)
    @test_throws ErrorException QAtlas.fetch(m, Energy(), PBC(0); Lx=4, Ly=0)
end

# ─────────────────────────────────────────────────────────────────────────────
# Section 3 (known-value) tests: exact diagonalisation vs the flux-free
# formula. The Lieb theorem states the ground state of the honeycomb
# Kitaev model sits in the all-plaquettes-positive flux sector, so ED
# of the actual spin Hamiltonian must match the flux-free-sector
# ansatz the QAtlas `fetch` implements. We cover (a) a single-bond
# trivial case, (b) a 2-site z-bond chain, and (c) a full 8-site
# honeycomb strip at Lx = Ly = 2 OBC.
# ─────────────────────────────────────────────────────────────────────────────
