# ─────────────────────────────────────────────────────────────────────────────
# Standalone test: TFIM ⟨σˣ_i⟩(t) sudden quench (issue #145).
#
# Validates the new `QuenchLocalMagnetization{:x}` quantity on both the
# OBC (Majorana covariance evolution) and `Infinite()` (closed-form
# k-integral) branches.
#
# References: Barouch–McCoy–Dresden, PRA 2 (1970); Calabrese–Essler–
# Fagotti, J. Stat. Mech. P07016 (2012).
# ─────────────────────────────────────────────────────────────────────────────

using QAtlas
using Test
using QuadGK: quadgk

# ─────────────────────────────────────────────────────────────────────
# Test parameters
# ─────────────────────────────────────────────────────────────────────
const J = 1.0

@testset "TFIM σˣ quench — t = 0 reproduces initial GS magnetisation" begin
    # Infinite: t=0 must equal the GS ⟨σˣ⟩ at h_0.
    for h_0 in (0.3, 0.7, 1.0, 1.5, 2.0, 3.5)
        for h_f in (0.2, 0.5, 1.0, 1.7, 4.0)
            m_0 = TFIM(; J=J, h=h_0)
            m_f = TFIM(; J=J, h=h_f)
            v0 = QAtlas.fetch(
                m_f, QuenchLocalMagnetization(:x), Infinite(); initial=m_0, t=0.0
            )
            gs = QAtlas.fetch(m_0, MagnetizationX(), Infinite(); beta=Inf)
            @test v0 ≈ gs atol = 1e-10
        end
    end

    # OBC: t=0 must equal the equilibrium LocalMagnetization(:x) at h_0,
    # central site (boundary effects negligible at the centre for N moderate).
    N = 24
    for h_0 in (0.4, 1.0, 1.8, 3.0)
        for h_f in (0.7, 1.3, 2.5)
            m_0 = TFIM(; J=J, h=h_0)
            m_f = TFIM(; J=J, h=h_f)
            mx_eq = QAtlas.fetch(m_0, LocalMagnetization(:x), OBC(N); beta=Inf)
            for i in (1, N ÷ 4, N ÷ 2, 3N ÷ 4, N)
                v0 = QAtlas.fetch(
                    m_f, QuenchLocalMagnetization(:x), OBC(N); initial=m_0, i=i, t=0.0
                )
                @test v0 ≈ mx_eq[i] atol = 1e-12
            end
        end
    end
end

@testset "TFIM σˣ quench — h_0 = h_f is time-independent" begin
    # Infinite branch
    for h in (0.3, 0.7, 1.0, 1.5, 2.5)
        m = TFIM(; J=J, h=h)
        gs = QAtlas.fetch(m, MagnetizationX(), Infinite(); beta=Inf)
        for t in (0.0, 0.1, 1.0, 3.7, 11.5)
            v = QAtlas.fetch(m, QuenchLocalMagnetization(:x), Infinite(); initial=m, t=t)
            @test v ≈ gs atol = 1e-12
        end
    end

    # OBC branch: at h_0 = h_f, ⟨σˣ_i⟩(t) = equilibrium GS value site-by-site.
    N = 16
    for h in (0.5, 1.2, 2.0)
        m = TFIM(; J=J, h=h)
        mx_eq = QAtlas.fetch(m, LocalMagnetization(:x), OBC(N); beta=Inf)
        for t in (0.0, 0.5, 2.3, 7.1)
            for i in (1, N ÷ 2, N)
                v = QAtlas.fetch(
                    m, QuenchLocalMagnetization(:x), OBC(N); initial=m, i=i, t=t
                )
                @test v ≈ mx_eq[i] atol = 1e-10
            end
        end
    end
end

@testset "TFIM σˣ quench — pinned reference value" begin
    # Pinned numerical value at (J=1, h_0=2, h_f=0.5, t=1.0) Infinite.
    # Generated by the implementation itself; serves as a regression
    # anchor (changes here will fail loudly until the new value is
    # cross-verified against literature / an independent integrator).
    m_0 = TFIM(; J=1.0, h=2.0)
    m_f = TFIM(; J=1.0, h=0.5)
    v = QAtlas.fetch(m_f, QuenchLocalMagnetization(:x), Infinite(); initial=m_0, t=1.0)
    @test v ≈ 0.28761380338145004 atol = 1e-8
end

@testset "TFIM σˣ quench — OBC large-N → Infinite agreement (central site)" begin
    # At sufficient N and away from the boundary (i ≈ N/2), the OBC value
    # must converge to the Infinite() closed-form integral.  Boundary-
    # induced reflections arrive at the centre at time t ≈ N/(4 v_max)
    # with v_max ≤ 2 max(J, h), so we keep t · max(2J, 2h_f) ≪ N/2.
    cases = [
        (h_0=0.5, h_f=1.5, t=0.7),
        (h_0=1.5, h_f=0.5, t=0.7),
        (h_0=2.0, h_f=0.5, t=1.0),
        (h_0=0.3, h_f=2.0, t=0.4),
    ]
    N = 80
    for c in cases
        m_0 = TFIM(; J=J, h=c.h_0)
        m_f = TFIM(; J=J, h=c.h_f)
        v_inf = QAtlas.fetch(
            m_f, QuenchLocalMagnetization(:x), Infinite(); initial=m_0, t=c.t
        )
        v_obc = QAtlas.fetch(
            m_f, QuenchLocalMagnetization(:x), OBC(N); initial=m_0, i=N ÷ 2, t=c.t
        )
        @test v_obc ≈ v_inf atol = 1e-4
    end
end

@testset "TFIM σˣ quench — long-time average matches GGE" begin
    # t → ∞ time average of the quench formula:
    #
    #   ⟨σˣ⟩_GGE = (1/π) ∫₀^π cos(2 θ_k^f) cos(2 Δθ_k) dk
    #
    # (the cos(2 Λ_k^f t) factor averages to zero for non-degenerate
    # Λ_k^f).  Independent integrand, computed directly here, then
    # compared to the trapezoidal time average of the dynamic value over
    # a sufficiently dense and long t-grid.

    function gge_value(J, h_0, h_f)
        integrand = function (k)
            ε_f = h_f - J * cos(k)
            ε_0 = h_0 - J * cos(k)
            Δ_k = J * sin(k)
            θf = atan(2 * Δ_k, 2 * ε_f)  # 2 θ_k^f
            θ0 = atan(2 * Δ_k, 2 * ε_0)  # 2 θ_k^0
            return cos(θf) * cos(θf - θ0)
        end
        val, _ = quadgk(integrand, 0.0, π; rtol=1e-12)
        return val / π
    end

    cases = [(h_0=2.0, h_f=0.5), (h_0=0.5, h_f=2.0), (h_0=0.3, h_f=1.7)]
    for c in cases
        m_0 = TFIM(; J=J, h=c.h_0)
        m_f = TFIM(; J=J, h=c.h_f)
        gge = gge_value(J, c.h_0, c.h_f)

        # Trapezoidal time average over t ∈ [t_min, t_max].  Skip
        # an initial transient to suppress finite-window ringing.
        t_min = 5.0
        t_max = 200.0
        nt = 4001
        ts = range(t_min, t_max; length=nt)
        dt = (t_max - t_min) / (nt - 1)
        S = 0.0
        for (idx, t) in enumerate(ts)
            v = QAtlas.fetch(
                m_f, QuenchLocalMagnetization(:x), Infinite(); initial=m_0, t=t
            )
            w = (idx == 1 || idx == nt) ? 0.5 : 1.0
            S += w * v
        end
        avg = S * dt / (t_max - t_min)
        @test avg ≈ gge atol = 5e-3
    end
end

@testset "TFIM σˣ quench — back-compat: LocalMagnetization(:x) unchanged" begin
    # Existing call sites use `LocalMagnetization(:x)` (no parameter) and
    # expect a Vector{Float64} with the equilibrium thermal magnetisation.
    # Verify the parametric refactor preserves this exactly.
    N = 12
    m = TFIM(; J=1.0, h=0.7)
    mx_old_style = QAtlas.fetch(m, LocalMagnetization(:x), OBC(N); beta=10.0)
    mx_new_style = QAtlas.fetch(m, LocalMagnetization(:x), OBC(N); beta=10.0)
    @test mx_old_style isa Vector{Float64}
    @test length(mx_old_style) == N
    @test mx_old_style ≈ mx_new_style atol = 1e-14
end

@testset "TFIM σˣ quench — input validation" begin
    m_0 = TFIM(; J=1.0, h=0.5)
    m_f = TFIM(; J=2.0, h=0.5)  # different J
    @test_throws ArgumentError QAtlas.fetch(
        m_f, QuenchLocalMagnetization(:x), Infinite(); initial=m_0, t=1.0
    )
    @test_throws ArgumentError QAtlas.fetch(
        m_f, QuenchLocalMagnetization(:x), OBC(8); initial=m_0, i=4, t=1.0
    )
    # Deprecated fused-name shim (#734): the `mode` kwarg/positional maps onto
    # the split types, and an unknown mode still errors.
    @test MagnetizationXLocal() === LocalMagnetization(:x)
    @test MagnetizationXLocal(:equilibrium) === LocalMagnetization(:x)
    @test MagnetizationXLocal(:quench) === QuenchLocalMagnetization(:x)
    @test MagnetizationXLocal(; mode=:quench) === QuenchLocalMagnetization(:x)
    @test_throws Exception MagnetizationXLocal(:bogus)
end

# ── Verification cards (WHY-correct plane) ─────────────────────────────────
@testset "TFIM σx-quench — verification cards" begin
    # t = 0: the quenched local σx equals the initial-state equilibrium
    # value. Mirrors the existing test's exact signatures (beta=Inf
    # required on the static MagnetizationX reference).
    let m0 = TFIM(; J=1.0, h=2.0), mf = TFIM(; J=1.0, h=0.5)
        verify(
            mf,
            QuenchLocalMagnetization(:x),
            Infinite();
            route=:limiting_case,
            fetch_kw=(; initial=m0, t=0.0),
            independent=QAtlas.fetch(m0, MagnetizationX(), Infinite(); beta=Inf),
            agree_within=1e-8,
            refs=["t=0: ⟨σx⟩(0) equals the initial-state equilibrium magnetization"],
        )
    end

    # No-quench: h0 = hf => time-independent at the equilibrium value
    let m = TFIM(; J=1.0, h=1.3)
        verify(
            m,
            QuenchLocalMagnetization(:x),
            Infinite();
            route=:limiting_case,
            fetch_kw=(; initial=m, t=3.7),
            independent=QAtlas.fetch(m, MagnetizationX(), Infinite(); beta=Inf),
            agree_within=1e-8,
            refs=["No-quench: σx expectation is stationary at the equilibrium value"],
        )
    end
end
