# ─────────────────────────────────────────────────────────────────────────────
# Transverse Field Ising Model — Generalised Gibbs Ensemble (GGE) stationary
# values for a sudden quench between two TFIM Hamiltonians.
#
# Setup.  The system starts in the ground state |ψ_0⟩ of the pre-quench
# TFIM with parameters (J, h_0) and is evolved by the post-quench TFIM
# with parameters (J, h_f) (the Ising coupling J is held fixed; only h
# is quenched, in line with the standard Calabrese–Essler–Fagotti
# convention).  Because both Hamiltonians are Bogoliubov-diagonal at
# every momentum mode k, every mode-occupation
#
#     n_k = ⟨c_k^† c_k⟩
#
# is an exact integral of motion (free fermions are integrable).  The
# long-time average of every local observable equals its expectation
# in the diagonal ensemble — equivalently, the *generalised Gibbs
# ensemble* (GGE) ρ_GGE = exp(−Σ_k λ_k n_k) / Z fixed by the {n_k}.
# See Rigol et al. PRL 98 (2007) for the general principle and
# Calabrese–Essler–Fagotti J. Stat. Mech. (2012) P07016 / P07022 for
# the TFIM-specific closed form.
#
# Bogoliubov angles.  Define the angle θ_k(h) by the diagonalisation
# of the BdG block at momentum k:
#
#     tan(2 θ_k(h)) = (J sin k) / (h - J cos k)
#
# (atan2 form below for branch safety).  The quench occupations are
#
#     n_k = sin²( θ_k(h_0) - θ_k(h_f) )
#
# and the GGE expectations of the per-site Hamiltonian and of σˣ are
#
#     ε_GGE = -(1/π) ∫₀^π dk · (Λ_k(h_f)/2) · (1 - 2 n_k)
#     ⟨σˣ⟩_GGE = (2/π) ∫₀^π dk · (h_f − J cos k)/Λ_k(h_f) · (1 - 2 n_k)
#
# with Λ_k(h) = 2 √(J² + h² − 2 J h cos k).  The factor (1 − 2 n_k)
# replaces the equilibrium tanh(βΛ/2): at h_0 = h_f (no quench)
# n_k ≡ 0 and one recovers the T = 0 ground-state expressions
# implemented in TFIM.jl / TFIM_thermal.jl.
#
# Energy conservation.  Because |ψ_0⟩ is the GS of H_0 and H_f shares
# the same momentum decomposition,
#
#     ⟨ψ_0 | H_f | ψ_0⟩ / N = ε_GGE,
#
# i.e. the GGE energy *equals* the (constant) energy of the initial
# state evaluated against the post-quench Hamiltonian.  This is the
# strongest cross-check: the same closed form arises from two
# physically distinct routes (long-time average vs. instantaneous
# expectation in the initial state).
# ─────────────────────────────────────────────────────────────────────────────

using QuadGK: quadgk

# ═══════════════════════════════════════════════════════════════════════════════
# Bogoliubov angle and quench occupation
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _tfim_two_theta(k, J, h) -> Float64

The Bogoliubov double-angle `2 θ_k(h)` of the TFIM at momentum `k`,

    2 θ_k(h) = atan2(J sin k, h − J cos k) ∈ (-π, π].

The atan2 form keeps the angle on the principal branch through
the critical point `h = J` and through `k = 0, π`, which a naive
`atan(J sin k / (h - J cos k))` misses (the denominator changes sign).
"""
@inline function _tfim_two_theta(k::Real, J::Real, h::Real)
    return atan(J * sin(k), h - J * cos(k))
end

"""
    _tfim_gge_occupation(k, J, h0, hf) -> Float64

Conserved mode occupation `n_k = sin²((θ_k(h0) − θ_k(hf)))`
generated by a sudden quench from initial transverse field `h0` to
final transverse field `hf` at momentum `k`.

Numerical detail: `Δ(2θ) = 2θ_k(h0) − 2θ_k(hf)` is computed via the
two-argument `atan` (atan2) for branch safety; we then divide by 2
inside `sin` to get `θ_k(h0) − θ_k(hf)`.
"""
@inline function _tfim_gge_occupation(k::Real, J::Real, h0::Real, hf::Real)
    Δ = _tfim_two_theta(k, J, h0) - _tfim_two_theta(k, J, hf)
    return sin(Δ / 2)^2
end

# ═══════════════════════════════════════════════════════════════════════════════
# Closed-form GGE quadratures (Infinite, per-site)
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _tfim_gge_energy_density(J, h0, hf) -> Float64

Per-site GGE energy density of the post-quench TFIM (J, hf) starting
from the ground state of (J, h0):

    ε_GGE = -(1/π) ∫₀^π dk · (Λ_k(hf) / 2) · (1 − 2 n_k(h0, hf))

with `Λ_k(h) = 2 √(J² + h² − 2 J h cos k)` and
`n_k = sin²(θ_k(h0) − θ_k(hf))`.

Sanity:
* `h0 == hf` ⇒ `n_k ≡ 0` ⇒ `ε_GGE = -(1/π) ∫ Λ/2 dk = ε_GS(hf)`.

The integral is evaluated via adaptive Gauss-Kronrod quadrature with
`rtol = 1e-10`.
"""
function _tfim_gge_energy_density(J::Real, h0::Real, hf::Real)
    integrand = k -> begin
        Λk = _tfim_dispersion(k, J, hf)
        n_k = _tfim_gge_occupation(k, J, h0, hf)
        (Λk / 2) * (1 - 2 * n_k)
    end
    val, _ = quadgk(integrand, 0.0, π; rtol=1e-10)
    return -val / π
end

"""
    _tfim_gge_magnetization_x(J, h0, hf) -> Float64

Per-site GGE transverse magnetisation `⟨σˣ⟩_GGE` of the post-quench
TFIM (J, hf) starting from the ground state of (J, h0):

    ⟨σˣ⟩_GGE = (2/π) ∫₀^π dk · (hf − J cos k)/Λ_k(hf) · (1 − 2 n_k)

The factor `(hf − J cos k)/Λ_k(hf)` equals `cos(2 θ_k(hf)) / 2`, so
equivalently

    ⟨σˣ⟩_GGE = (1/π) ∫₀^π dk · cos(2 θ_k(hf)) · (1 − 2 n_k).

We use the explicit `(hf - J cos k)/Λ_k` form to share the integrand
structure with the equilibrium MagnetizationX routine in
TFIM_thermal.jl.

Sanity:
* `h0 == hf` ⇒ `n_k ≡ 0` ⇒ recovers the T = 0 / β = ∞ equilibrium
  value `(2/π) ∫ (h − J cos k)/Λ_k dk`.
"""
function _tfim_gge_magnetization_x(J::Real, h0::Real, hf::Real)
    integrand = k -> begin
        A = hf - J * cos(k)
        Λk = _tfim_dispersion(k, J, hf)
        n_k = _tfim_gge_occupation(k, J, h0, hf)
        (A / Λk) * (1 - 2 * n_k)
    end
    val, _ = quadgk(integrand, 0.0, π; rtol=1e-10)
    return (2 / π) * val
end

# ═══════════════════════════════════════════════════════════════════════════════
# fetch dispatch
# ═══════════════════════════════════════════════════════════════════════════════

"""
    fetch(model_f::TFIM, ::GGEValue{Energy{:per_site}}, ::Infinite;
          initial::TFIM, kwargs...) -> Float64

Per-site Generalised Gibbs Ensemble (GGE) energy density of the
infinite TFIM after a sudden quench `(J, h_0) → (J, h_f)`, with
`model_f = TFIM(J = J, h = h_f)` and `initial = TFIM(J = J, h = h_0)`.

The closed form

    ε_GGE = -(1/π) ∫₀^π dk · (Λ_k(h_f)/2) · (1 − 2 n_k(h_0, h_f))

is the long-time average reached by the post-quench evolution; it
also equals the (time-independent) energy expectation of the initial
state |ψ_0⟩ in the post-quench Hamiltonian H_f, which serves as the
canonical energy-conservation cross-check.

# Required kwarg

- `initial::TFIM` — pre-quench TFIM whose ground state is the initial
  state.  The Ising couplings must match (`initial.J == model_f.J`);
  a mismatch throws `DomainError`.

# Example

```julia
fetch(TFIM(J = 1.0, h = 0.5), GGEValue(Energy(:per_site)), Infinite();
      initial = TFIM(J = 1.0, h = 2.0))
```

# References

- Rigol et al., *Relaxation in a Completely Integrable Many-Body
  Quantum System*, PRL **98**, 050405 (2007).
- Calabrese, Essler, Fagotti, *Quantum Quench in the Transverse
  Field Ising Chain*, J. Stat. Mech. (2012) P07016, P07022.
"""
function fetch(
    model_f::TFIM,
    ::GGEValue{Energy{:per_site}},
    ::Infinite;
    initial::TFIM,
    kwargs...,
)
    _check_quench_couplings(model_f, initial)
    return _tfim_gge_energy_density(model_f.J, initial.h, model_f.h)
end

# `Energy()` (`:natural`) routes to `:per_site` for Infinite TFIM —
# same convention as the equilibrium Energy methods.
function fetch(
    model_f::TFIM,
    ::GGEValue{Energy{:natural}},
    ::Infinite;
    initial::TFIM,
    kwargs...,
)
    return fetch(
        model_f, GGEValue(Energy{:per_site}()), Infinite(); initial=initial, kwargs...
    )
end

"""
    fetch(model_f::TFIM, ::GGEValue{MagnetizationX}, ::Infinite;
          initial::TFIM, kwargs...) -> Float64

GGE stationary value of the transverse magnetisation `⟨σˣ⟩` of the
infinite TFIM after a sudden quench `(J, h_0) → (J, h_f)`:

    ⟨σˣ⟩_GGE = (2/π) ∫₀^π dk · (h_f − J cos k)/Λ_k(h_f) · (1 − 2 n_k)

with `n_k = sin²(θ_k(h_0) − θ_k(h_f))`.

# Required kwarg

- `initial::TFIM` — pre-quench TFIM (must share `J`).

# References

See [`fetch(::TFIM, ::GGEValue{Energy{:per_site}}, ::Infinite; ...)`].
"""
function fetch(
    model_f::TFIM, ::GGEValue{MagnetizationX}, ::Infinite; initial::TFIM, kwargs...
)
    _check_quench_couplings(model_f, initial)
    return _tfim_gge_magnetization_x(model_f.J, initial.h, model_f.h)
end

# ═══════════════════════════════════════════════════════════════════════════════
# Internal helpers
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _check_quench_couplings(model_f::TFIM, initial::TFIM)

Validate that a TFIM quench preserves the Ising coupling `J`.  The
GGE closed forms in `TFIM_gge.jl` only treat `h`-quenches; a `J`
quench is not in the standard Calabrese–Essler–Fagotti framework and
the `n_k` formula derived above does not apply.
"""
function _check_quench_couplings(model_f::TFIM, initial::TFIM)
    if !isapprox(model_f.J, initial.J; rtol=1e-12, atol=0.0)
        throw(
            DomainError(
                (model_f.J, initial.J),
                "TFIM GGE: only `h`-quenches are supported; the Ising couplings " *
                "of `initial` ($(initial.J)) and post-quench model ($(model_f.J)) " *
                "must agree.",
            ),
        )
    end
    return nothing
end
