# CONVENTION
#   Hamiltonian: H = J · Σ_{i<j} S_i · S_j / d(i,j)²  with spin S = σ/2
#   Observable:  Spin S = σ/2 (QAtlas-wide spin convention; see docs/src/conventions.md)

# ─────────────────────────────────────────────────────────────────────────────
# Haldane-Shastry chain — spin-1/2 inverse-square Heisenberg chain
#
# Hamiltonian (Haldane 1988, Shastry 1988):
#
#   H = J · Σ_{i < j}  S_i · S_j / d(i,j)^2
#
# where d(i,j) is the chord distance on the periodic chain of N sites:
#
#   d(i, j) = (N / π) · sin(π (i - j) / N)
#
# In the thermodynamic limit d(i, j) → |i - j| and the Hamiltonian
# reduces to a long-range inverse-square chain:
#
#   H = J · Σ_{i < j}  S_i · S_j / (j - i)^2
#
# The model is exactly solvable. The ground state is the Gutzwiller-
# projected free-fermion (RVB) wavefunction, and the entire spectrum
# is generated by Yangian-degenerate spinon excitations with linear
# dispersion in the long-wavelength limit (Haldane 1988, 1991).
#
# Ground-state energy density (closed form, Haldane 1988):
#
#   E_0 / N = -π^2 J / 24
#
# Single-spinon dispersion (Haldane 1988):
#
#   ε(k) = (J / 2) k (π - k),       k ∈ [0, π]
#
# Sound velocity at the gapless points k = 0, π:
#
#   v_s = |dε/dk|_{k = 0, π} = π J / 2
#
# coinciding with the Heisenberg sound velocity (both chains are c = 1
# CFT in the long-wavelength limit), so v_s plus c = 1 fix the leading
# low-T thermodynamics. The full finite-T NLIE / fractional-statistics
# closed forms are tracked separately in issue #524.
#
# References
# ==========
#
#   - F. D. M. Haldane, [Haldane1988](@cite) — model
#     definition + Gutzwiller GS + spinon dispersion
#   - B. S. Shastry, [Shastry1988](@cite) — independent
#     introduction with explicit spectrum
#   - F. D. M. Haldane, [Haldane1991](@cite) — Yangian
#     algebra and full spectrum
#   - F. D. M. Haldane, Z. N. C. Ha, J. C. Talstra, D. Bernard, V.
#     Pasquier, [Haldane1992](@cite) — Yangian highest
#     weight basis and dynamical correlators
# ─────────────────────────────────────────────────────────────────────────────

"""
    HaldaneShastry(; J::Real = 1.0) <: AbstractQAtlasModel

Spin-1/2 Haldane-Shastry chain — inverse-square Heisenberg chain on the
periodic chord-distance lattice (Haldane 1988, Shastry 1988):

    H = J · Σ_{i < j}  S_i · S_j / d(i, j)^2,   d(i,j) = (N/π) sin(π(i-j)/N)

In the thermodynamic limit d(i, j) → |i - j|. The model is exactly
solvable with Yangian symmetry; the ground state is the Gutzwiller-
projected free-fermion wavefunction and the entire spectrum is
generated by spinons with dispersion ε(k) = (J/2) k(π - k).

# Fields

- `J::Float64` — antiferromagnetic exchange (J > 0). The 1/r^2 fall-off
  is locked by the model definition.

# References

- F. D. M. Haldane, Phys. Rev. Lett. **60**, 635 (1988).
- B. S. Shastry, Phys. Rev. Lett. **60**, 639 (1988).
- F. D. M. Haldane, Phys. Rev. Lett. **66**, 1529 (1991).
"""
struct HaldaneShastry <: AbstractQAtlasModel
    J::Float64
    function HaldaneShastry(J::Float64)
        J > 0 || throw(DomainError(J, "HaldaneShastry coupling J must be > 0"))
        return new(J)
    end
end
HaldaneShastry(; J::Real=1.0) = HaldaneShastry(Float64(J))

# ═══════════════════════════════════════════════════════════════════════════════
# Ground-state energy density — exact closed form
# ═══════════════════════════════════════════════════════════════════════════════

"""
    fetch(::HaldaneShastry, ::GroundStateEnergyDensity, ::Infinite; kwargs...) -> Float64

Exact thermodynamic-limit ground-state energy density of the Haldane-
Shastry chain (Haldane 1988, Shastry 1988):

    E_0 / N = -π^2 J / 24

This value is finite-N exact for any N divisible by 2 — the Gutzwiller-
projected free-fermion wavefunction is an exact eigenstate of the
chord-distance Hamiltonian — so no finite-size correction enters.

# References

- F. D. M. Haldane, Phys. Rev. Lett. **60**, 635 (1988), eq. (4).
- B. S. Shastry, Phys. Rev. Lett. **60**, 639 (1988).

# Example

```jldoctest
julia> QAtlas.fetch(HaldaneShastry(), GroundStateEnergyDensity(), Infinite())
-0.4112335167120566
```
"""
function fetch(m::HaldaneShastry, ::GroundStateEnergyDensity, ::Infinite; kwargs...)
    isempty(kwargs) || @warn(
        "fetch(HaldaneShastry, GroundStateEnergyDensity, Infinite) received unrecognized kwargs; they are ignored.",
        kwargs=collect(keys(kwargs))
    )
    return -π^2 * m.J / 24
end

# ═══════════════════════════════════════════════════════════════════════════════
# Spinon dispersion — exported helper
# ═══════════════════════════════════════════════════════════════════════════════

"""
    haldane_shastry_spinon_dispersion(model::HaldaneShastry, k::Real) -> Float64

Single-spinon dispersion of the Haldane-Shastry chain (Haldane 1988):

    ε(k) = (J / 2) k (π - k),   k ∈ [0, π]

The dispersion is gapless at the two zone-boundary points k = 0 and
k = π with sound velocity v_s = π J / 2 (same as the SU(2)-symmetric
Heisenberg point — both flow to the same c = 1 SU(2)₁ WZW CFT).

Throws `DomainError` outside the spinon Brillouin zone [0, π].

# References

- F. D. M. Haldane, Phys. Rev. Lett. **60**, 635 (1988), eq. (5).
"""
function haldane_shastry_spinon_dispersion(m::HaldaneShastry, k::Real)
    0 ≤ k ≤ π || throw(DomainError(k, "spinon momentum k must lie in [0, π]"))
    return (m.J / 2) * k * (π - k)
end

"""
    haldane_shastry_sound_velocity(model::HaldaneShastry) -> Float64

Long-wavelength sound velocity of the c = 1 SU(2)_1 WZW critical
theory describing the Haldane-Shastry chain:

    v_s = π J / 2

Identical to the SU(2)-symmetric Heisenberg sound velocity; the two
chains share the same low-energy CFT despite the very different
microscopic interaction range.

# References

- F. D. M. Haldane, Phys. Rev. Lett. **60**, 635 (1988).
- I. Affleck, Nucl. Phys. B **265**, 409 (1986) — SU(2)_1 WZW central
  charge and velocity for Heisenberg-class chains.
"""
haldane_shastry_sound_velocity(m::HaldaneShastry) = π * m.J / 2
