# docs/atlas/generate.jl
#
# docs-as-view (prototype, TFIM): renders docs/src/atlas/tfim.md as a pure
# VIEW over {src registry claims} + {test/INVENTORY cards}. No src change,
# no test execution. Implements the leverage risk-linter (M3): a claimed
# hub with zero STRUCTURAL corroboration is flagged. named-point canonical;
# @sweep curves listed as parametric.
#
# Run: julia --startup-file=no docs/atlas/generate.jl
const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
include(joinpath(ROOT, "test", "harness", "atlas", "AtlasInventory.jl"))
include(joinpath(ROOT, "test", "harness", "atlas", "AtlasRegistry.jl"))
using .AtlasInventory, .AtlasRegistry

cards = AtlasInventory.scan_dir(joinpath(ROOT, "test", "models", "quantum", "TFIM"))
claims = AtlasRegistry.scan_registry(
    joinpath(ROOT, "src", "models", "quantum", "TFIM", "TFIM_registry.jl"))

bycard = Dict{String,Vector{AtlasInventory.Card}}()
for c in cards
    push!(get!(bycard, c.hub, AtlasInventory.Card[]), c)
end
nstruct(h) = count(c -> c.independence == "structural", get(bycard, h, AtlasInventory.Card[]))
nassert(h) = count(c -> c.independence == "asserted", get(bycard, h, AtlasInventory.Card[]))

claimed = sort(unique(c.hub for c in claims))
covered = filter(h -> nstruct(h) > 0, claimed)
assert_only = filter(h -> nstruct(h) == 0 && nassert(h) > 0, claimed)
uncov = filter(h -> nstruct(h) == 0 && nassert(h) == 0, claimed)

io = IOBuffer()
P(s...) = println(io, string(s...))

P("# TFIM — Verified Exact-Solution Atlas")
P("")
P("!!! note \"Generated view (prototype)\"")
P("    Auto-generated by `docs/atlas/generate.jl` as a pure VIEW over the ",
  "src registry (`TFIM_registry.jl`) and the static test inventory ",
  "(`test/INVENTORY.jsonl`). No source or test code is executed here. ",
  "v2 framework vertical slice for issue #369 / Discussion #379.")
P("")
P("## Coverage")
P("")
P("| | count |")
P("|---|---|")
P("| Hubs `src` claims (registry) | ", length(claimed), " |")
P("| With >=1 **structural** corroboration | ", length(covered), " |")
P("| Only **asserted** (honor-system) corroboration | ", length(assert_only), " |")
P("| **Uncorroborated** (risk) | ", length(uncov), " |")
P("| Inventory cards scanned | ", length(cards), " |")
P("")

P("## ⚠️ Leverage risk-linter")
P("")
P("Anti-join: `src` claims the hub **and** zero *structural* ",
  "(mechanically-independent) corroboration cards exist. `:sum_rule` / ",
  "`:delegation_invariant` / `:limiting_case` are honor-system and do ",
  "**not** clear this flag (review finding M3).")
P("")
if isempty(uncov) && isempty(assert_only)
    P("All claimed TFIM hubs carry at least one structural corroboration. ✅")
else
    P("| hub | status |")
    P("|---|---|")
    for h in assert_only
        P("| `", h, "` | ⚠️ asserted-only (", nassert(h), " honor-system card(s), 0 structural) |")
    end
    for h in uncov
        P("| `", h, "` | ❌ uncorroborated (src claims it; no card) |")
    end
end
P("")

P("## Hubs")
P("")
clby = Dict{String,Vector{AtlasRegistry.Claim}}()
for c in claims
    push!(get!(clby, c.hub, AtlasRegistry.Claim[]), c)
end
for h in claimed
    cl = first(clby[h])
    P("### `", h, "`")
    P("")
    P("- **src claim:** method `", cl.method, "`, reliability `",
      cl.reliability, "`", isempty(cl.refs) ? "" : string(", refs: ", cl.refs))
    isempty(cl.notes) || P("- ", cl.notes)
    cs = get(bycard, h, AtlasInventory.Card[])
    if isempty(cs)
        P("- _No corroboration card. Flagged by the risk-linter._")
        P("")
        continue
    end
    pts = filter(c -> c.arity == "point", cs)
    crv = filter(c -> c.arity != "point", cs)
    P("")
    P("| regime | mechanism | independence | refs | file |")
    P("|---|---|---|---|---|")
    for c in vcat(pts, crv)
        badge = c.independence == "structural" ? "🟢 structural" : "🟡 asserted"
        P("| `", c.regime, "` | `", c.mechanism, "` | ", badge, " | ",
          c.refs, " | `", c.file, "` |")
    end
    P("")
end

out = joinpath(ROOT, "docs", "src", "atlas", "tfim.md")
mkpath(dirname(out))
write(out, String(take!(io)))
println("wrote ", out, "  (", length(claimed), " hubs, ", length(cards), " cards, ",
        length(uncov), " uncorroborated, ", length(assert_only), " asserted-only)")
