# docs/atlas/generate.jl
# docs-as-view (repo-wide). Pure VIEW over {all *_registry.jl claims} +
# {whole test/ INVENTORY}. No src change, no test execution, fetch/register
# framework untouched. M3 risk-linter (structural-only anti-join).
const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
include(joinpath(ROOT, "test", "harness", "atlas", "AtlasInventory.jl"))
include(joinpath(ROOT, "test", "harness", "atlas", "AtlasRegistry.jl"))
using .AtlasInventory, .AtlasRegistry

cards = AtlasInventory.scan_dir(joinpath(ROOT, "test"))
AtlasInventory.write_inventory(joinpath(ROOT, "test", "INVENTORY.jsonl"), cards)

regfiles = String[]
for (root, _, fs) in walkdir(joinpath(ROOT, "src"))
    for f in fs
        endswith(f, "_registry.jl") && push!(regfiles, joinpath(root, f))
    end
end
claims = AtlasRegistry.Claim[]
regfail = String[]
for rf in regfiles
    try
        append!(claims, AtlasRegistry.scan_registry(rf))
    catch
        push!(regfail, replace(rf, ROOT * "/" => ""))
    end
end

bycard = Dict{String,Vector{AtlasInventory.Card}}()
for c in cards
    push!(get!(bycard, c.hub, AtlasInventory.Card[]), c)
end
nstruct(h) = count(c -> c.independence == "structural", get(bycard, h, AtlasInventory.Card[]))
nassert(h) = count(c -> c.independence == "asserted", get(bycard, h, AtlasInventory.Card[]))

claimed = sort(unique(c.hub for c in claims))
covered = filter(h -> nstruct(h) > 0, claimed)
assertonly = filter(h -> nstruct(h) == 0 && nassert(h) > 0, claimed)
uncov = filter(h -> nstruct(h) == 0 && nassert(h) == 0, claimed)

modelof(h) = first(split(h, "/"))
models = sort(unique(modelof(h) for h in claimed))

io = IOBuffer()
P(s...) = println(io, string(s...))
P("# QAtlas — Verified Exact-Solution Atlas")
P("")
P("!!! note \"Generated view (v2 prototype, repo-wide)\"")
P("    Auto-generated by `docs/atlas/generate.jl` as a pure VIEW over all ",
  "`*_registry.jl` claims and the whole-`test/` static inventory ",
  "(`test/INVENTORY.jsonl`). No source/test executed; fetch/register ",
  "framework untouched. Assurance labels PROVISIONAL (RES not wired; ",
  "regime vocabulary per-model pending — most non-TFIM cards show ",
  "`@sweep`, a graceful regime-resolution gap, not card omission).")
P("")
P("## Coverage (all models)")
P("")
P("| | count |")
P("|---|---|")
P("| Hubs `src` claims (registry) | ", length(claimed), " |")
P("| With >=1 **structural** corroboration | ", length(covered), " |")
P("| Only **asserted** (honor-system) | ", length(assertonly), " |")
P("| **Uncorroborated** (risk) | ", length(uncov), " |")
P("| Inventory cards scanned (whole test/) | ", length(cards), " |")
P("| Registry files parsed | ", length(regfiles) - length(regfail), " / ", length(regfiles), " |")
P("| Models | ", length(models), " |")
P("")
P("## ⚠️ Leverage risk-linter (structural-only anti-join, M3)")
P("")
P("`src` claims the hub **and** zero *structural* corroboration cards. ",
  "`:sum_rule` / `:delegation` / `:limiting_case` are honor-system and do ",
  "not clear this flag.")
P("")
P("| count | bucket |")
P("|---|---|")
P("| ", length(uncov), " | ❌ uncorroborated (src claims; no card) |")
P("| ", length(assertonly), " | ⚠️ asserted-only (honor-system only) |")
P("| ", length(covered), " | 🟢 structurally corroborated |")
P("")
P("## Per-model breakdown")
P("")
P("| model | claimed | structural | asserted-only | uncorroborated |")
P("|---|---|---|---|---|")
for m in models
    hs = filter(h -> modelof(h) == m, claimed)
    P("| `", m, "` | ", length(hs), " | ",
      count(h -> nstruct(h) > 0, hs), " | ",
      count(h -> nstruct(h) == 0 && nassert(h) > 0, hs), " | ",
      count(h -> nstruct(h) == 0 && nassert(h) == 0, hs), " |")
end
P("")
if !isempty(regfail)
    P("!!! warning \"Registry parse failures (", length(regfail), ")\"")
    for r in regfail
        P("    - `", r, "`")
    end
    P("")
end
P("## Hubs")
P("")
clby = Dict{String,Vector{AtlasRegistry.Claim}}()
for c in claims
    push!(get!(clby, c.hub, AtlasRegistry.Claim[]), c)
end
for h in claimed
    cl = first(clby[h])
    cs = get(bycard, h, AtlasInventory.Card[])
    badge = isempty(cs) ? "❌" : (nstruct(h) > 0 ? "🟢" : "⚠️")
    P("### ", badge, " `", h, "`")
    P("")
    P("- src claim: method `", cl.method, "`, reliability `", cl.reliability, "`",
      isempty(cl.refs) ? "" : string(", refs: ", cl.refs))
    isempty(cl.notes) || P("- ", cl.notes)
    if isempty(cs)
        P("- _No corroboration card (risk-linter flag)._")
        P("")
        continue
    end
    P("")
    P("| regime | mechanism | independence | refs | file |")
    P("|---|---|---|---|---|")
    for c in cs
        b = c.independence == "structural" ? "🟢 structural" : "🟡 asserted"
        P("| `", c.regime, "` | `", c.mechanism, "` | ", b, " | ", c.refs,
          " | `", c.file, "` |")
    end
    P("")
end

out = joinpath(ROOT, "docs", "src", "atlas", "index.md")
mkpath(dirname(out))
write(out, String(take!(io)))
println("wrote ", out, "  models=", length(models), " hubs=", length(claimed),
        " cards=", length(cards), " regfail=", length(regfail),
        " (struct=", length(covered), " assertonly=", length(assertonly),
        " uncov=", length(uncov), ")")
