# docs/atlas/graph_export.jl — render the QAtlas knowledge graph as an
# Obsidian-style force-directed graph view inside the Documenter site.
#
# Unlike generate.jl (a pure-AST scanner), this loads QAtlas and walks the live
# edge stores (REGISTRY + REALIZES via links.jl): the physical-validity network
# — models realize classes, classes predict quantities, bounds constrain
# quantities, models delegate quantities — plus the coherence self-diagnosis
# (undeveloped classes / delegation-without-realizes) colored as gaps, so the
# verification and the visualization come out of the same graph.
#
# Run: julia --project=. docs/atlas/graph_export.jl  →  docs/src/atlas/graph.md

using QAtlas

const REG = QAtlas.REGISTRY
const REAL = QAtlas.REALIZES

_short(T) = replace(string(T), "QAtlas." => "")
_js(s) = replace(string(s), "\\" => "\\\\", "\"" => "\\\"")

# ── collect nodes + edges (only nodes that appear in an edge) ────────────────
nodes = Dict{String,NamedTuple}()      # id => (label, group, title)
edges = Vector{NamedTuple}()           # (from, to, label, gap)

addnode!(id, label, group, title) = get!(nodes, id, (label=label, group=group, title=title))

_is_uni(T) = T <: QAtlas.Universality
_is_bnd(T) = T <: QAtlas.Bound
_class(T) = T.parameters[1]
_concrete(T) = !_is_uni(T) && !_is_bnd(T)

realized_classes = sort(unique(r.class for r in REAL))
undeveloped = Set(c for c in realized_classes if isempty(QAtlas.predicts(c)))

# realizes : model → class
for r in REAL
    m = _short(r.model)
    addnode!("M:" * m, m, "model", "model")
    addnode!("C:" * string(r.class), string(r.class), "class", "universality class")
    push!(edges, (from="M:" * m, to="C:" * string(r.class), label="realizes", gap=false))
end

# predicts : class → quantity
for e in REG
    _is_uni(e.model) || continue
    c = _class(e.model)
    q = _short(e.quantity)
    addnode!("C:" * string(c), string(c), "class", "universality class")
    addnode!("Q:" * q, q, "quantity", "quantity")
    push!(edges, (from="C:" * string(c), to="Q:" * q, label="predicts", gap=false))
end

# bounds : bound-domain → quantity
for e in REG
    _is_bnd(e.model) || continue
    d = _class(e.model)
    q = _short(e.quantity)
    addnode!("B:" * string(d), string(d), "bound", "bound domain")
    addnode!("Q:" * q, q, "quantity", "quantity")
    push!(
        edges,
        (
            from="B:" * string(d),
            to="Q:" * q,
            label="bounds(" * string(e.direction) * ")",
            gap=false,
        ),
    )
end

# delegates : model → quantity  (gap-colored when the model realizes no class)
for e in REG
    e.method === :delegation && _concrete(e.model) || continue
    m = _short(e.model)
    q = _short(e.quantity)
    isgap = !any(r -> r.model === e.model, REAL)
    addnode!("M:" * m, m, "model", "model")
    addnode!("Q:" * q, q, "quantity", "quantity")
    push!(edges, (from="M:" * m, to="Q:" * q, label="delegates", gap=isgap))
end

# ── emit vis-network JSON ────────────────────────────────────────────────────
function node_json(id, n)
    grp = if startswith(id, "C:") && (id[3:end] in [string(c) for c in undeveloped])
        "gap"
    else
        n.group
    end
    return "{id:\"$(_js(id))\",label:\"$(_js(n.label))\",group:\"$(grp)\",title:\"$(_js(n.title)): $(_js(n.label))\"}"
end
node_lines = join([node_json(id, n) for (id, n) in nodes], ",\n      ")

function edge_json(e)
    col = e.gap ? ",color:{color:\"#e8a33d\"},dashes:true" : ""
    return "{from:\"$(_js(e.from))\",to:\"$(_js(e.to))\",label:\"$(_js(e.label))\",arrows:\"to\",font:{size:9,color:\"#888\"}$(col)}"
end
edge_lines = join([edge_json(e) for e in edges], ",\n      ")

n_models = count(id -> startswith(id, "M:"), keys(nodes))
n_classes = count(id -> startswith(id, "C:"), keys(nodes))
n_bounds = count(id -> startswith(id, "B:"), keys(nodes))
n_quant = count(id -> startswith(id, "Q:"), keys(nodes))

page = """
# Knowledge graph

The QAtlas vault as a force-directed network — **models** realize **universality
classes**, classes **predict** quantities, **bounds** constrain quantities, and
models **delegate** quantities to their class.  Orange dashed = a coherence
*gap* (an undeveloped class, or a delegation whose model realizes no class).
Drag nodes; hover for type.

*Generated by `docs/atlas/graph_export.jl` from the live registry —
$(length(nodes)) nodes ($(n_models) models, $(n_classes) classes,
$(n_bounds) bound domains, $(n_quant) quantities), $(length(edges)) edges.*

```@raw html
<div id="qatlas-graph" style="width:100%;height:720px;border:1px solid var(--light-color,#ddd);border-radius:6px;"></div>
<script src="../../assets/vis-network.min.js"></script>
<script>
(function(){
  function draw(){
    var el = document.getElementById("qatlas-graph");
    if (!el) return;
    if (typeof vis === "undefined") {
      el.innerHTML = "<p style='padding:1em'>vis-network failed to load — the bundled assets/vis-network.min.js did not load.</p>";
      return;
    }
    var nodes = new vis.DataSet([
      $(node_lines)
  ]);
  var edges = new vis.DataSet([
      $(edge_lines)
  ]);
  var groups = {
    model:    {color:{background:"#4f8cc9",border:"#2b5d8a"},shape:"dot"},
    class:    {color:{background:"#9b6cc9",border:"#6b3f96"},shape:"diamond"},
    bound:    {color:{background:"#c95f5f",border:"#8a2b2b"},shape:"triangle"},
    quantity: {color:{background:"#5fae6f",border:"#2b7a3f"},shape:"box"},
    gap:      {color:{background:"#e8a33d",border:"#b87410"},shape:"diamond"}
  };
    var network = new vis.Network(
      el,
      {nodes:nodes, edges:edges},
      {
        groups: groups,
        nodes: {font:{size:12}},
        edges: {smooth:{type:"continuous"}},
        physics: {barnesHut:{gravitationalConstant:-8000,springLength:120,springConstant:0.04},
                  stabilization:{iterations:200}},
        interaction: {hover:true, tooltipDelay:120}
      }
    );
    network.once("stabilizationIterationsDone", function(){ network.fit(); });
  }
  if (document.readyState === "complete") { draw(); }
  else { window.addEventListener("load", draw); }
})();
</script>
```
"""

open(joinpath(@__DIR__, "..", "src", "atlas", "graph.md"), "w") do io
    write(io, page)
end
println("graph.md written: ", length(nodes), " nodes, ", length(edges), " edges")
