# docs/atlas/graph_export.jl — render the QAtlas knowledge graph as an
# Obsidian-style force-directed graph view inside the Documenter site, using the
# Quartz graph engine (d3-force + PixiJS) ported to a standalone, data-driven
# bundle: docs/src/assets/qatlas-graph.js (built from
# obsidian-remote-ssh/docs-site/qatlas-graph-entry.ts via esbuild).
#
# This loads QAtlas and walks the live edge stores (REGISTRY + REALIZES via
# links.jl) — models realize classes, classes predict quantities, bounds
# constrain quantities, models delegate quantities — plus the coherence
# self-diagnosis (undeveloped classes / delegation-without-realizes) colored as
# gaps.  Verification and visualization come out of the same graph.
#
# Run: julia --project=. docs/atlas/graph_export.jl  →  docs/src/atlas/graph.md

using QAtlas

const REG = QAtlas.REGISTRY
const REAL = QAtlas.REALIZES

_short(T) = replace(string(T), "QAtlas." => "")
_js(s) = replace(string(s), "\\" => "\\\\", "\"" => "\\\"")
_clean(s) = occursin(r"^[A-Za-z0-9_]+$", s)

# ── collect nodes + edges (only nodes that appear in an edge) ────────────────
nodes = Dict{String,NamedTuple}()      # id => (text, group, url)
edges = Vector{NamedTuple}()           # (from, to, gap)

addnode!(id, text, group, url) = get!(nodes, id, (text=text, group=group, url=url))

_is_uni(T) = T <: QAtlas.Universality
_is_bnd(T) = T <: QAtlas.Bound
_class(T) = T.parameters[1]
_concrete(T) = !_is_uni(T) && !_is_bnd(T)

_model_url(name) = _clean(name) ? "../models/$(name)/" : ""
_quantity_url(name) = _clean(name) ? "../quantities/$(name)/" : ""

realized_classes = sort(unique(r.class for r in REAL))
undeveloped = Set(c for c in realized_classes if isempty(QAtlas.predicts(c)))

# realizes : model → class
for r in REAL
    m = _short(r.model)
    addnode!("M:" * m, m, "model", _model_url(m))
    addnode!(
        "C:" * string(r.class), string(r.class), r.class in undeveloped ? "gap" : "class", ""
    )
    push!(edges, (from="M:" * m, to="C:" * string(r.class), gap=false))
end

# predicts : class → quantity
for e in REG
    _is_uni(e.model) || continue
    c = _class(e.model)
    q = _short(e.quantity)
    addnode!("C:" * string(c), string(c), c in undeveloped ? "gap" : "class", "")
    addnode!("Q:" * q, q, "quantity", _quantity_url(q))
    push!(edges, (from="C:" * string(c), to="Q:" * q, gap=false))
end

# bounds : bound-domain → quantity
for e in REG
    _is_bnd(e.model) || continue
    d = _class(e.model)
    q = _short(e.quantity)
    addnode!("B:" * string(d), string(d), "bound", "")
    addnode!("Q:" * q, q, "quantity", _quantity_url(q))
    push!(edges, (from="B:" * string(d), to="Q:" * q, gap=false))
end

# delegates : model → quantity  (gap-colored when the model realizes no class)
for e in REG
    e.method === :delegation && _concrete(e.model) || continue
    m = _short(e.model)
    q = _short(e.quantity)
    isgap = !any(r -> r.model === e.model, REAL)
    addnode!("M:" * m, m, "model", _model_url(m))
    addnode!("Q:" * q, q, "quantity", _quantity_url(q))
    push!(edges, (from="M:" * m, to="Q:" * q, gap=isgap))
end

# ── emit QAtlasGraph JSON ─────────────────────────────────────────────────────
node_json(id, n) =
    "{id:\"$(_js(id))\",text:\"$(_js(n.text))\",group:\"$(n.group)\",url:\"$(_js(n.url))\"}"
nodes_js = join([node_json(id, n) for (id, n) in nodes], ",\n      ")
edge_json(e) = "{source:\"$(_js(e.from))\",target:\"$(_js(e.to))\",gap:$(e.gap)}"
edges_js = join([edge_json(e) for e in edges], ",\n      ")

n_models = count(id -> startswith(id, "M:"), keys(nodes))
n_classes = count(id -> startswith(id, "C:"), keys(nodes))
n_bounds = count(id -> startswith(id, "B:"), keys(nodes))
n_quant = count(id -> startswith(id, "Q:"), keys(nodes))

page = """
# Knowledge graph

The QAtlas vault as a force-directed network — **models** realize **universality
classes**, classes **predict** quantities, **bounds** constrain quantities, and
models **delegate** quantities to their class.  Orange = a coherence *gap* (an
undeveloped class, or a delegation whose model realizes no class).  Drag nodes,
scroll to zoom, hover to highlight neighbours, click a model/quantity to open its
page.

*Rendered by the Quartz graph engine (d3-force + PixiJS), ported to a standalone
bundle (`assets/qatlas-graph.js`).  Generated by `docs/atlas/graph_export.jl`
from the live registry — $(length(nodes)) nodes ($(n_models) models,
$(n_classes) classes, $(n_bounds) bound domains, $(n_quant) quantities),
$(length(edges)) edges.*

```@raw html
<div id="qatlas-graph" style="width:100%;height:720px;border:1px solid var(--light-color,#ddd);border-radius:6px;"></div>
<script>
(function(){
  var DATA = {
    nodes: [
      $(nodes_js)
    ],
    links: [
      $(edges_js)
    ]
  };
  var CFG = {
    drag: true, zoom: true, repelForce: 0.7, centerForce: 0.3,
    linkDistance: 38, fontSize: 0.6, opacityScale: 1.1, focusOnHover: true,
    labelColor: getComputedStyle(document.documentElement).getPropertyValue("--body-color") || "#2b2b2b"
  };
  function go(){
    var el = document.getElementById("qatlas-graph");
    if (!el) return;
    if (window.QAtlasGraph) { window.QAtlasGraph.render(el, DATA, CFG); return; }
    var root = location.pathname.split("atlas/graph")[0];
    var s = document.createElement("script");
    s.src = root + "assets/qatlas-graph.js";
    s.onload = function(){ if (window.QAtlasGraph) window.QAtlasGraph.render(el, DATA, CFG); };
    s.onerror = function(){ el.innerHTML = "<p style='padding:1em'>graph bundle failed to load from " + s.src + "</p>"; };
    document.head.appendChild(s);
  }
  if (document.readyState === "complete") { go(); }
  else { window.addEventListener("load", go); }
})();
</script>
```
"""

open(joinpath(@__DIR__, "..", "src", "atlas", "graph.md"), "w") do io
    write(io, page)
end
println("graph.md written: ", length(nodes), " nodes, ", length(edges), " edges")
